version: '3'
services: 
  postgres: 
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_PASSWORD: Elraphty#1
  redis:
    image: 'redis:latest'
  api: 
    build: 
      dockerfile: Dockerfile.dev
      context:  ./server
    volumes: 
      - /app/node_modules
      - ./server:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=Elraphty#1
      - PGPORT=5432
  client:
    stdin_open: true
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx: 
    restart: always
    depends_on:
      - api
      - client
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - '3050:80'